[package]
name = "random-art"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
rand = "0.8.5"
thiserror = "1.0.69"
clap = { version = "4.5.26", features = ["derive"] }
macroquad = "0.4.13"